### ISSUE TITLE
Can not install from Moodle plugins directory

### ISSUE THREAD

**Issue by caiadogithub** [dbnschools/moodle-theme_rebel#1]
Install plugins from the Moodle plugins directory

Downloading theme_rebel ... OK
Validating theme_rebel ... Error
  [Error] Extracted file not found [{"file":"rebel\/templates\/core_message\/"}] 
Installation aborted due to validation failure

**Comment by dbnschools** [comment]
I know what the issue is.  I'll have a fix shortly.  I left a folder in the
template directory empty after we changed a feature.

Chris

**Comment by dbnschools** [comment]
Fixed in version 1.3
