### ISSUE TITLE
Menu - Site Administration

### ISSUE THREAD

**Issue by chrisinabztf** [dbnschools/moodle-theme_rebel#10]
Somehow I get, logged in as an normal moodle-user (without adminrights), the option to got to the website-administration. ...for sure I have no rights for this, I get an Access-Denied if I click on it.

Shouldn't it not be shown to normal users?

![menue_site_administration](https://user-images.githubusercontent.com/50485041/102586702-ea38c700-410a-11eb-8e95-1132cc29df91.png)
![menue_site_administration_accessDenied](https://user-images.githubusercontent.com/50485041/102586700-e9a03080-410a-11eb-826e-0d10c27d392b.png)

**Comment by dbnschools** [comment]
Be sure to be running Rebel 1.7.4.  I do know one of the versions I didn't have the permissions set to remove this from view for non-admins but it has been fixed in 1.7.3 and .4 for sure.
