### ISSUE TITLE
Content Bank - Link

### ISSUE THREAD

**Issue by chrisinabztf** [dbnschools/moodle-theme_rebel#12]
If I use the standard Boost Theme, I've a link (being on the Dashboard) on the left side which points me to the H5P-Content-Bank.

![ContentBankDashboard](https://user-images.githubusercontent.com/50485041/102805886-32324500-43bc-11eb-888c-6f4b63606cdf.png)

This link should show up in the top menu (or at least: somewhere), within the Dashboard, with rebel as well - isn't it?

![ContentBankDashboardNot](https://user-images.githubusercontent.com/50485041/102806149-a40a8e80-43bc-11eb-9988-a1d34ae9b97d.png)

**Comment by dbnschools** [comment]
It might have been missing from previous versions but it is included in current versions.  See the screenshot of the teacher dashboard on the plugin homepage.  

Things change rapidly, so always include what version of the theme you are using.
