### ISSUE TITLE
In Moodle 3.10+ the course deletion functionality broke for ADMIN User after applying theme

### ISSUE THREAD

**Issue by Namgyal-Yolmo** [dbnschools/moodle-theme_rebel#13]
This was working perfectly fine till Moodle 3.9 but seems to be broken in Moodle 3.10+

Steps to replicate.
1. Use Moodle Instance with version 3.10+ latest, install Rebel and apply.
2. Create a course as an Admin User.
3. Go to site administration --> Courses --> Manage courses and categories
4. Try to delete the course. Message 'You do not have the permission to delete this course' is displayed. 

While using the default BOOST Theme this works perfectly fine.
Please Note: I have checked only in one instance.

**Comment by dbnschools** [comment]
I see the issue.  I'll be investigating.

**Comment by dbnschools** [comment]
Change line 157 of the core_renderer.php file to this:

`if ($PAGE->pagelayout !== 'coursecategory' && $PAGE->pagetype !== 'course-management' && $PAGE->pagetype !== 'course-delete') {`

I added this to the line:
` && $PAGE->pagetype !== 'course-delete'`
And that fixes the issue.

I'll get a new version published on Moodle.org and git soon.

**Comment by dbnschools** [comment]
Published

**Comment by Namgyal-Yolmo** [comment]
Thank You.

Regards,
Namgyal Yolmo
