### ISSUE TITLE
Appearance -> Themes -> Rebel -> Branding Settings -> Brand Logo Image

### ISSUE THREAD

**Issue by Namgyal-Yolmo** [dbnschools/moodle-theme_rebel#3]
The description says "This image is displayed in the header area and footer area. It should be a small sized logo".

Uploaded a custom logo and observed the header logo actually changes. But nothing happened at the footer. We were expecting this would replace the default moodle logo at the footer. 

Not sure if this is expected. But letting DEVs know.

**Comment by dbnschools** [comment]
I had planned to add it to the footer.  I will make sure it is in a future release or will change the wording if we decide not to include it there.

**Comment by dbnschools** [comment]
Is fixed and added to footer in the 1.7 release.  Almost ready to push out.
