### ISSUE TITLE
Preset Dropdown

### ISSUE THREAD

**Issue by chrisinabztf** [dbnschools/moodle-theme_rebel#4]
Since the upgrade to 1.6 I can upload a predefined preset file, but I don't have the option to choose it (as it was before or as it is in standard boost theme).

Am I doing something wrong?

**Comment by dbnschools** [comment]
You are correct.  I removed the chooser but now I realize I need to add it back so that custom ones can be selected.  I forgot about that.  I will have a fix released soon.

**Comment by dbnschools** [comment]
I have put the code back into the settings so that you can choose the uploaded preset.  It will be in the next release.

**Comment by dbnschools** [comment]
Fixed and published with version 1.7
