### ISSUE TITLE
Can i be translated?

### ISSUE THREAD

**Issue by dinism** [dbnschools/moodle-theme_rebel#6]
![imagem](https://user-images.githubusercontent.com/14828021/101519250-dfe43380-397a-11eb-826d-16b426dae71a.png)

**Comment by dbnschools** [comment]
That is from the Easy Enrollment Plugin.  There are two issues on this page:  
1) The popup is just a quick php page and that title is hardcoded into the page.  I am not sure how I can get a language string to appear here.
2) Below that is an actual image with text and not very ADA compliant.  I will loop the main developer on this and see what we can do.

Thanks, Chris

**Comment by dinism** [comment]
THANKS A LOT!
